name: Deploy to Production

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: [self-hosted, production]
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Copy files to production
      run: rsync -r --delete --exclude=.git --exclude=__pycache__ --exclude=RPSChialisp/__pycache__ ./ ${{ secrets.DEPLOY_FOLDER }}
